const products = [
  {
    id: "BK0996",
    name: "Batik Korpri Toya",
    brand: "Toya",
    thumbnail: "images/BK0996.png",
    images: ["images/BK0996.png", "images/BK0996-2.png", "images/BK0996-3.png"],
    material: "Katun",
    initialPrice: "Rp175.000",
    afterPrice: "",
    categories: "Korpri",
    discount: false,
    review: 16,
    sales: 156,
    description: "",
    colors: ["Biru"],
    sizes: ["M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: "BK0999",
    name: "Blouse Korpri Toya",
    brand: "Toya",
    thumbnail: "images/BK0999.jpeg",
    images: [
      "images/BK0999.jpeg",
      "images/BK0999-2.png",
      "images/BK0999-3.png",
    ],
    material: "Katun",
    initialPrice: "Rp220.000",
    afterPrice: "",
    categories: "Korpri",
    discount: false,
    review: 64,
    sales: 147,
    description: "",
    colors: ["Biru"],
    sizes: ["M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "BK1086",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK1086.png",
    images: ["images/BK1086.png", "images/BK1086-2.png", "images/BK0974-3.png"],
    material: "Katun",
    initialPrice: "Rp260.000",
    afterPrice: "",
    categories: "Lengan Pendek",
    discount: false,
    review: 53,
    sales: 235,
    description: "",
    colors: ["Merah", "Cokelat", "Biru"],
    sizes: ["3XL", "4XL", "5XL"],
  },
  {
    id: "BK0974",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK0974.png",
    images: ["images/BK0974.png", "images/BK0974-2.png", "images/BK0974-3.png"],
    material: "Katun",
    initialPrice: "Rp285.000",
    afterPrice: "",
    categories: "Lengan Pendek",
    discount: false,
    review: 85,
    sales: 325,
    description: "",
    colors: ["Hitam", "Biru", "Maroon"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "BK0984",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK0984.png",
    images: ["images/BK0984.png", "images/BK0984-2.png", "images/BK0984-3.png"],
    material: "Katun",
    initialPrice: "Rp300.000",
    afterPrice: "",
    categories: "Lengan Pendek",
    discount: false,
    review: 65,
    sales: 72,
    description: "",
    colors: ["Hitam"],
    sizes: ["3XL", "4XL", "6XL"],
  },
  {
    id: "BK1095",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK1095.png",
    images: ["images/BK1095.png", "images/BK1095-2.png", "images/BK1095-3.png"],
    material: "Katun",
    initialPrice: "Rp255.000",
    afterPrice: "",
    categories: "Lengan Pendek",
    discount: false,
    review: 83,
    sales: 143,
    description: "",
    colors: ["Kuning", "Cokelat"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "BK0977",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK0977.jpg",
    images: [
      "images/BK0977.jpg",
      "images/BK0977-2.jpg",
      "images/BK0977-3.jpg",
      "images/BK0977-4.jpg",
    ],
    material: "Katun",
    initialPrice: "Rp305.000",
    afterPrice: "",
    categories: "Lengan Panjang",
    discount: false,
    review: 84,
    sales: 421,
    description: "",
    colors: ["Cokelat", "Hijau", "Abu-abu"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "BK1035",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK1035.png",
    images: [
      "images/BK1035.png",
      "images/BK1035-2.png",
      "images/BK1035-3.png",
      "images/BK1035-4.png",
    ],
    material: "Katun",
    initialPrice: "Rp300.000",
    afterPrice: "",
    categories: "Lengan Panjang",
    discount: false,
    review: 72,
    sales: 232,
    description: "",
    colors: ["Hitam", "Navy"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "BK1082",
    name: "Batik Hanspeter",
    brand: "Hanspeter",
    thumbnail: "images/BK1082.png",
    images: ["images/BK1082.png", "images/BK1082-2.png"],
    material: "Katun",
    initialPrice: "Rp180.000",
    afterPrice: "",
    categories: "Lengan Panjang",
    discount: false,
    review: 62,
    sales: 423,
    description: "",
    colors: ["Cokelat", "Biru"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "BK1092",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK1092.png",
    images: ["images/BK1092.png", "images/BK1092-2.png"],
    material: "Katun",
    initialPrice: "Rp265.000",
    afterPrice: "",
    categories: "Lengan Panjang",
    discount: false,
    review: 62,
    sales: 423,
    description: "",
    colors: ["Biru", "Abu", "Hijau", "Maroon"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "BK1039",
    name: "Batik Elok Joyo",
    brand: "Elok Joyo",
    thumbnail: "images/BK1039.png",
    images: ["images/BK1039.png", "images/BK1039-2.png", "images/BK1039-3.png"],
    material: "Katun",
    initialPrice: "Rp300.000",
    afterPrice: "",
    categories: "Lengan Panjang",
    discount: false,
    review: 62,
    sales: 423,
    description: "",
    colors: ["Cokelat", "Hitam Orange", "Hitam cokelat", "Biru"],
    sizes: ["M", "L", "XL"],
  },
];

export default products;
